// Entidades
Table Agencia {
  id int [pk, increment]
  nombre varchar
  direccion varchar
  telefono varchar
}

Table Vehiculo {
  id int [pk, increment]
  placa varchar
  marca varchar
  modelo varchar
  estado varchar
  precio_por_dia decimal
  agencia_id int [ref: > Agencia.id]
}

Table Cliente {
  id int [pk, increment]
  nombre varchar
  email varchar
  telefono varchar
  direccion varchar
}

Table Reserva {
  id int [pk, increment]
  fecha_inicio date
  fecha_fin date
  estado varchar
  cliente_id int [ref: > Cliente.id]
  vehiculo_id int [ref: > Vehiculo.id]
}

Table Pago {
  id int [pk, increment]
  fecha_pago date
  monto decimal
  metodo varchar
  reserva_id int [ref: > Reserva.id, unique]
}

// Relaciones
// Una Agencia tiene muchos Vehículos
// Un Cliente puede tener varias Reservas
// Un Vehículo puede tener varias Reservas
// Una Reserva tiene un único Pago
